# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CacheServiceClass' do
  
   pod 'SDWebImage', '~> 4.0.0-beta2'
   pod 'SVProgressHUD', '~> 2.0.4'

end
